### ISSUE TITLE
Have to re-approve app every time OBS/Overlay is openned

### ISSUE THREAD

**Issue by Jaggernaut555** [DerTyp876/ts5-obs-overlay#14] opened 2023-01-11 02:15 UTC
Having to re-approve the app every time someone were to open OBS is a pretty bad experience. There's not really any documentation about the remote app API (and it's highly subject to change) so I'm not entirely sure why that is/how to fix it or I'd give it a shot.

![image](https://user-images.githubusercontent.com/5661214/211702146-c8e2647e-71ce-4d42-a78e-bc1c69288211.png)

**Comment by DerTyp876** [comment] 2023-01-11 09:33
I don't know if this is fixable with ts remote apps. Every time we send an auth message to the ts client, even if a working "apiKey" is provided in the payload, I get a popup and a new "apiKey" from TeamSpeak. 

I have tried checking if an "apiKey" is already in the cache and then not sending an auth message. Unfortunately, this does not work because we need to send an authentication message to the ts client to register our app to receive websockets.

My conclusion is that this is the expected behavior of the TeamSpeak client. Api keys are probably just there to store a session.

**Comment by DerTyp876** [comment] 2023-01-11 09:35
I didn't mean to close the issue instantly.

**Comment by DerTyp876** [comment] 2023-01-11 12:17
The overlay now uses the cache to save the api key. 
Which means restarting OBS does not cause a new api key or popup.
Restarting TS5 will still cause a new api key and popup

**Closed by DerTyp876** 2023-01-11 12:17 UTC
Labels: enhancement
